# Copyright 2018 The Outline Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: node_js

node_js:
  - "10"

cache:
  yarn: true
  directories:
    - $HOME/.cache/bower
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  # Cache OutineBot's credentials.
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
  # https://docs.travis-ci.com/user/languages/javascript-with-nodejs#travis-ci-supports-yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"

stages:
  - name: build and unit test
    if: type != cron
  - name: tag
    if: type = cron
  - name: package
    if: tag =~ ^daily
  - name: android
    if: tag =~ ^android
  - name: ios
    if: tag =~ ^ios

# Stages with the same name define multiple jobs which run in parallel.
# To make it more apparent in the Travis UI exactly what each job is
# doing, we add a descriptive environment variable.
jobs:
  include:
    # Ideally, we would split this stage in some way, e.g. by component or by
    # build/test commands, to make it clearer in the Travis UI exactly which
    # command failed. However, since each stage incurs a significantly start-up
    # cost, we combine test and build commands for all components into one fast
    # stage.
    - stage: build and unit test
      script:
        - yarn gulp build --platform=browser
        - yarn do scripts/test

    - stage: tag
      script:
        - RELEASE_NAME=daily-$(date -I)
        - curl --data '{"tag_name":"'$RELEASE_NAME'","name":"'$RELEASE_NAME'","prerelease":true}' https://api.github.com/repos/Jigsaw-Code/outline-client/releases?access_token=$CI_USER_TOKEN

    - stage: package
      env:
        - DESC=android
      sudo: required
      services: docker
      script: ./tools/build/build.sh yarn gulp build --platform=android

    # https://www.electron.build/multi-platform-build
    - stage: package
      env:
        - DESC=windows
      sudo: required
      services: docker
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
      script:
        - docker pull electronuserland/builder:wine
        - docker run --rm
            -v ${PWD}:/project
            -v ~/.cache/electron:/root/.cache/electron
            -v ~/.cache/electron-builder:/root/.cache/electron-builder
            electronuserland/builder:wine
            /bin/bash -c "apt update && apt install -y rsync && yarn do src/electron/package" || travis_terminate $?

    - stage: package
      os: osx
      language: objective-c
      osx_image: xcode9.4
      env:
        - DESC=macos
      script:
        # This stage does not produce a binary because we cannot sign or provision the application on CI yet.
        - yarn && yarn gulp build --platform=osx

    - stage: package
      os: osx
      language: objective-c
      osx_image: xcode9.4
      env:
        - DESC=ios
      script:
        - yarn && yarn do apple/scripts/ios_package_remote

    - stage: android
      sudo: required
      services: docker
      env:
        # Encrypted key store password. Stored in $KEY_STORE_PASSWORD.
        - secure: "LnpZs5k0SStiaT9dePXdoUFLJjz4GrwEfdlSb4oUcGUPw8Ci4oy4503mydGjxYZ6Uz2LhnDFb4rYi2E+ynkovBlhUSJoOxkmSWa83iE3Zn+0U4lQLWC70EaVflPnERElZZmRgFG6OeWY9J6YIMBhl1DAcXDl1oOqcq0Nbl/3/OWN36WKyEg801nZD39QYH4l33CIMP+PEjKGBIN1MGN9WsCeJFjVsRoZZhseevxb75mzYT3sCvOuJLJ6CTtzHMGHDqi+HP/yL/jnXYOheiVJXDJTmTq9Wd6vzIa+WIemmBhLNlh8OuxzffBD3BC/wqXtk8LsK5Xx9Y8np+TZ5e8NbSTQowZ6oSwBHEsk8EhqOf41eknxNuQfZGkH1kujhqNkKzpnl6y09Wxki4gZphhKpT1cqkQG37TsqS4z1NsOI48kwK3gDiTH+BdV+yzFIGg6F7uVxBmhuw5XzWqlH+WWM98wcRfL9hgY74bdjs/a5ALRhx8mJAH65MiUvKUqSLHy/4pNb70u7xyIpk8JyxzyjMwKqNJj7I2PbpaORQeGUXoJwm9hp0su3cSFCsTsGKDzHqwxFdSCP7Ff62wqy5gYKLeZiIyA+lo0Q+mYLwWE4klj07oVnH9IrAm0jn9kfqB+mIs/07frouIvWRc/boi5hu6KUkRDSyWPYvL5xmi4jjw="
        # Encrypted key password. Stored in $KEY_PASSWORD.
        - secure: "M1eL5hArI1DMdDUuu42gBVSmUb6pH435eA5FkolpdUnfC5xv4er1r459XOvYRiixqALGLZ4rcg5I3ZzkqLH0r5gex7h0L7TQtCTh9I+GFMoo75U0rKBr6fLkt6lUaahG6FfX0HN5BFZ1CoKjtBHOxkG6hMmq6zjNHVg8+DiYcXvftH/pUtx8KSVojdSMb0BvxZVAB7lo4exmM/upjGCf/oHMYuYm94JGtPt5GEj0lGep7twHzlkYHve0q0WFS/UgBvDbksIy4yxwUut40jIJ/neUiBz2lujz6YPGL+lzwpyNEn+sNEXXMQFx9YQkCYFP/pXGFY1y/UYBd+cnppWlXQaomljBDORn9M5Be7qx/ekt7fdio9q71hJffcVm1t6J+wiVdXJmwYM5l8V9RI4+9uECsm/esxEStyZVXuZnRRYkDF3T6bR/2STD/6ik1gH/3//F7Ld25nJ2jtISkPNf5C0/3eXdtdSLCoiVoC2byRTyDBkxBZyHWLwAksAIpOG3Gj08WUN8l6VSPJyn9swAdwuEchYpOm1M+5frc5s6jIii/SzukFE3OtyAKP7YiCU+Pcctsq6muMdg5ky+7QuYtn9nbo/yIsZbEedBIGwSlWAkNjEANUka75ILt5Nv2r5Yo/XiESqYlEI6sufybX6RPApS8B1Y9ikXdcFb/irWsdA="
        # Encrypted key alias. Stored in $KEY_ALIAS.
        - secure: "kUUN6t8txRUrLSbR9KMSbA0LT2juKjt0MA9Do8w/2uV6r33KrhRkSM2Of8+GApNGwm469ZVS5bYNQ/+y81YlleNGzbpTYl4Lr2Dw+x9L9U04sWRPN8R59bqWHvBQiL8UwzbYj8C5/plPJ+ojr9v92ppzWYQGjAozAWxA0YA7PHFfs4VoUMKYlF88djCHfgt6jlbYJVYLo+G+jtj7VyK1v6KhcXyYz2wn9JnO/Szhi152UdkqQUMpBvHEnfF+GdWn8o7nP3htF+S46tBu1pL0AKsxzsT7Bp0XLYtehzqsiset/eRpNdWGx2cl0Bl+7HBI2Aa1zbxJ5gU7lyp7NvURJRkNa3/h6VQyl7z8mo3Z7xG4teAcG/scT5hW+2ElXfC2bubRRQtokggNxh4TUI3b75P+/mP6B7AzzY6RTOWHOipu6+2LtHdcWQZpRi1ORzFw/1rVIRmMtGn6UMwD0XkA7ZGzq3SgKiw77HSOyWP800EPv7P7B0miEFhno4cmlYLnWQroaqY9Kv6ISqjcFMGksUU7tTflC/ZqiKYXI1ESFS0cI/FtaLprcz8BYWHUrfP8+/Ivqvgl/i9c4SuVVIaZ7bd4SnV+Qq6CNVjrOdLCMpy5AozOz8tNix4E1b0qv0jCZ/OKeFax8+A/udqN+XlKqx3FegGyf7rT7bNQ3tgK6Ec="
      script:
        - openssl aes-256-cbc -K $encrypted_cb15c65d6aeb_key -iv $encrypted_cb15c65d6aeb_iv -in keystore.p12.enc -out keystore.p12 -d
        - ./tools/build/build.sh yarn gulp build --platform=android --release --KEYSTORE=keystore.p12 --KEYALIAS=$KEY_ALIAS --STOREPASS=$KEY_STORE_PASSWORD --KEYPASS=$KEY_PASSWORD

    - stage: ios
      os: osx
      language: objective-c
      osx_image: xcode9.4
      script:
        - yarn && yarn do apple/scripts/ios_release_remote

deploy:
  provider: releases
  api_key:
    secure: "rVCXm4JU1B39WCvDKm7tAYoEznEkVG+MgLJTYBQTiOsalh5kjc5rGrzBtWANEZbAHOEAxx3vmUL8XMNOuekB44rubqRBJTKvnjqhekNWH+4Jga/7Y6r8HkktI17F0vkWmcILe2yJNXjX6Tb7gPS4xQkTHUM4dykAmiuNGQ7v557TmtZxGAR4M61h2pEv6LsDiH4UmlPcr0UPUz/Igam2//rMx8y+YQgIJuFINQJOnOz19q4Vg+Bnk4OO4sNKY6EtVO/4o8onbdOCJ1Il6JH82CTZmutGurCf3xl2+NTnsjakcirviZvXoZxk6d9FgMd4croEPRA95rlze9ODqyJRp0z8QbLjaoJChJf0B1Mds9mvolMPtLwOi++bHyPedpe9/9VCey4/geB8iISdI5wd6FuvixtdOZeirOJMqYfQrfwvlJS0BFDy4W70Ei9EJ3Dz8/1pHj47WddNdqREhFIMACG4Wjtp+tp1IZcooNDfvGA3rZONTxV6ZYnELj1+slX5I9HGFFcgUOvDibod/DO5fjF6L1ujaliFKZBzjQq/srFJFqsFD4V4cX99ZFWcDZDrWpllFh5KKB2BrskgKsEe7n6QarswlVzbTEJobhKXPnaV3RAWTFJKh28+Yt65UMB4vZJR4VwvXG3WJd7+e5Sqo/MIF6bujhkzW/E75Ym82xo="
  file_glob: true
  file:
    - platforms/android/app/build/outputs/apk/**/*.apk
    - platforms/ios/Outline.ipa
    - build/windows/dist/*.exe
  skip_cleanup: true
  on:
    tags: true

env:
  global:
    # Encrypted Apple Developer password for outline-app-manager@google.com. Stored in $FASTLANE_PASSWORD.
    - secure: "HMZwvxT4MEGN53r6vZQBPf2iOyFGpZyFtADt3vmbbCRl4432zsx2ANh5JZhjFnK7U6CkpfFodVew1tZBqqEdnpLtNUfif1aVzFyVo9RmCUTTpK7eWG7b+q1HCIZDxwhb64y/wGY83+JCdtfhbw4Xk5egek0/Zhl3H6yGcOV4eo+yTjVpNbzYHJY1lmWp9fhp52e+PiMea6FURNI7mUxepc+eRez3/QkN/xAf/RTQ/yvRIjeJEfgSXUEFZo/Z85xa6R1WZpKxzLLSgG60AddZztcxNfVZMYkkM5w18I2OjmfLfQjt4QFrwxevO+ubjEyqybnkI6SUCT/AmfDbfplkpB6tYM/8FW65HeIxsupGttCphRDtdoYk4JMIKjNmdGk6u9wIurkgoQO0wShP9H3KQw6hAOTBMTAJYd9das5A7+1yxkoiR4UvHr29Hi6yehRwo9W9pSCA6v2nNqG0rp9twcZIK1LZe5CC4UdbkEd92APzKaXUgsfvRyuMPK8rL2jFujnt5pPqhmclBVMTwPNWr8K8EbzTaV+4VhYxQswoydMa44qXvzdX02KRUAUB4udNkhWNkIunEg/Kj96e4EwcRzJEXmPvJexqHH0yNyBqwDXmP08Yq12HsQYh1P+2zTywBQ8ygJRWWXSBwoYEROU1TmXE6U9MO3NLb/gdYzw2oOQ="
    # Encrypted fastlane match passphrase for decrypting JigsawCode/outline-apple-credentials. Stored in $MATCH_PASSWORD.
    - secure: "Ay8YFbYmV1/a+8uHBZFEIVrlzglGu3l2RohnjAVyX6T3K99/562VleQRigjlYUbqPGv8RMJX44DlXaGOyvBtPw9br5tDaV2fDqdr5/IUQcdPFY7D6+pI3BX8Rq0r1xIkj+q3ADx1Vy70GJiBvfNYrGdCYNTDlNvbTTKTZJSgP23Q55VjEESd9k+SYyLmM92vY/QbJDWTb0bh1EIj3i/I5cZSFTqXzeNUClHD086bCY8ewVcDO6zJwdp4Wo1PS7oL9dkJO+cvot2qjeuAIqh5LVdznEzpOBZ3hAkb8eCmC+0PPSGaJCC+W5RL5sVMRU4HF/gK/BzainXu7Rc1RiECLbr8Htf3WiULCumlCIWKa4PWyw/qYE1YDmXNirTirwajI0b2nkotTfA9WCtJ72vzLtNs1oSXp1afQBIJCR+KWTgqqVODV4wrSFu4MA2Kv+eJZo4yV86U/K4g5yep+93mSjXAnzRVhLVK/zKtqKpx38nu9AeHuwlJGQf9iMTOER9/wM3/kixhHdwE/NLoP6oswdKdz53lofK5wlUahvMvtHTAALKZuK9HW78IVDElMuH3wElmiywIdKrA3o/+60F8++0FhwehXP71TJ+u4Byg3j1QEeTEz8nZGaWCKqWAc5082fmEAHCb8PCYZ5m88Piid6Tuu9y7yNgZSWFMa5iUXDg="
